[package]
name = "optimist-calculator"
version = "0.1.0"
edition = "2021"
reqwest-json = "0.6"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-sdk = "1.14.11"
tokio = "0.2"
serde = { version = "1.0", features = ["derive"] }
reqwest = "0.10.8"
serde = "1.0.115"
serde_derive = "1.0.115"

